[package]
name = "lr_rust_shared_structs"
version = "0.1.0"
edition = "2024"
description = "shared_structs sub library for lr_rust."
license = "MIT"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"

[features]
lr1 = []
